### ISSUE TITLE
confused by input

### ISSUE THREAD

**Issue by sailseem** [ram-compbio/CANDO#3]
Dear developer,
     I just found out about this package, which is great, well, I am quite new to this. So, I am getting a little bit confused about input? 
Can I input like some proteins or uniprot ID which in some certain pathway to predict which compound could activate/deactivate it? How can I do this? And, these output compounds are already in your database or can be selected from another big database like zinc?    I am not sure if I make myself clear and hope you can understand. Thank you for your valuable time and sorry for these silly questions.

**Comment by willmangione** [comment]
Hi Sailseem, 

Thanks for your interest in our code, and your questions are not silly! To start, you can easily load one of our CANDO objects with the "load_version()" function, like so: 

`import cando as cnd` 
`cando = cnd.load_version(v='v2.3', protlib='homo_sapien', i_score='dCxP')`

Then you have a CANDO object loaded with our v2.3 compound library (~13k drugs/compounds) and their interaction scores with 8,385 human protein structures and models. If you want to reduce that set to only your proteins of interest, you can use the "protein_set" parameter instead, which will filter the proteins in the object to those matching your input list. Set this parameter to the path of the file containing each UniProt ID of interest on separate lines. Here's what it would look like if your file was named "my-proteins.txt":

`cando = cnd.load_version(v='v2.3', protlib='homo_sapien', i_score='dCxP', protein_set='my-proteins.txt')`

**Note: if none of your UniProt IDs are present in our protein library, there will be no proteins in the CANDO object.**

From here you can either loop through the compound/protein objects manually using the object-oriented setup, or use a function like "canpredict_denovo()" to find which compounds/drugs interact the most with proteins in your set. Please consult the tutorial/API for more information on how to run that. Also note that our scores are merely "interactions" and have no direct way of implying activation/deactivation, so please keep that in mind. 

In regards to your question about the source of our compounds, our libraries are primarily made up of those from [DrugBank ](https://go.drugbank.com/), but you can easily add any compound using the "generate_signature()" and "add_cmpd()" functions. All you need is a .mol structure file. Let's say your compound file is "my-cmpd.mol":

`cnd.generate_signature('my-cmpd.mol', org='homo_sapien', i_score='dCxP', out='my-cmpd-sig.tsv')`
`cando.add_cmpd(new_sig='my-cmpd-sig.tsv', new_name='my_cmpd')`

Your compound will be added to the CANDO object and will have a corresponding ID that will be printed to the command line. From there you can use the "get_compound()" function to retrieve it and look at its scores. There are also a ton of other functions in the API/tutorial that will help you in your analyses regarding both compounds and proteins. 

Hope this helps - let me know if you have any questions!

**Comment by sailseem** [comment]
Dear,
    I am realllllly appreciate your kindly and detailed reply, how nice of you! I feel so warm, basically, I got your point, let me explore a little bit and get back to you if i got further questions. Thanks a lottttttt!!!
